/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness check */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/modules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List modules */
        get: operations["list_modules_modules_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/modules/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a module by slug */
        get: operations["get_module_modules__slug__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List projects */
        get: operations["list_projects_projects_get"];
        put?: never;
        /** Import a spec (validates, persists, runs shop diff §8) */
        post: operations["create_project_projects_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get hydrated project */
        get: operations["get_project_projects__project_id__get"];
        put?: never;
        post?: never;
        /** Soft-delete a project */
        delete: operations["delete_project_projects__project_id__delete"];
        options?: never;
        head?: never;
        /** Update project status */
        patch: operations["update_project_projects__project_id__patch"];
        trace?: never;
    };
    "/projects/{project_id}/materials/{material_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Toggle a material's checked state */
        patch: operations["update_material_projects__project_id__materials__material_id__patch"];
        trace?: never;
    };
    "/projects/{project_id}/tools/{tool_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Toggle a tool's checked / owned state */
        patch: operations["update_tool_projects__project_id__tools__tool_id__patch"];
        trace?: never;
    };
    "/projects/{project_id}/steps/{step_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Toggle a step's completed state / set its note */
        patch: operations["update_step_projects__project_id__steps__step_id__patch"];
        trace?: never;
    };
    "/projects/{project_id}/retrospective": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Upsert the project retrospective */
        patch: operations["upsert_retrospective_projects__project_id__retrospective_patch"];
        trace?: never;
    };
    "/shop/inventory": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List My Shop */
        get: operations["list_inventory_shop_inventory_get"];
        put?: never;
        /** Add a tool to My Shop */
        post: operations["add_inventory_shop_inventory_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/shop/inventory/{inventory_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove a tool from My Shop */
        delete: operations["delete_inventory_shop_inventory__inventory_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/photos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List a project's photos */
        get: operations["list_photos_projects__project_id__photos_get"];
        put?: never;
        /** Upload a progress photo (multipart; optional step_id) */
        post: operations["upload_photo_projects__project_id__photos_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/photos/{photo_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a photo */
        delete: operations["delete_photo_photos__photo_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/generate/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start a generation session from the setup payload (mock 1d) */
        post: operations["start_session_generate_sessions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/generate/sessions/{session_id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Send one user turn, get the agent's reply (mock 1e) */
        post: operations["send_message_generate_sessions__session_id__messages_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/generate/sessions/{session_id}/finalize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Emit the full §6 spec as strict JSON (mock 1e → 1f) */
        post: operations["finalize_session_generate_sessions__session_id__finalize_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/research/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Re-populate research resources[] via web search (§7.2) */
        post: operations["refresh_research_projects__project_id__research_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_upload_photo_projects__project_id__photos_post */
        Body_upload_photo_projects__project_id__photos_post: {
            /** File */
            file: string;
            /** Step Id */
            step_id?: number | null;
            /** Caption */
            caption?: string | null;
        };
        /**
         * BudgetBand
         * @description Generation setup budget band (§7.1 / mock 1d): Under $30 / $30–75 / $75+.
         *
         *     NOTE (judgment call — confirm before forking): the docs give display labels,
         *     not wire tokens. These machine values are inferred.
         * @enum {string}
         */
        BudgetBand: "under_30" | "30_to_75" | "over_75";
        /**
         * Candidate
         * @description A proposed candidate project for vague/'surprise me' input (§7.1). The
         *     ``id`` is stable within the session and is echoed back via
         *     ``GenerateMessageCreate.select_candidate_id`` to pick it.
         */
        Candidate: {
            /**
             * Id
             * @description Stable within the session; used to select this candidate.
             */
            id: string;
            /** Title */
            title: string;
            /** Summary */
            summary: string;
            difficulty?: components["schemas"]["Difficulty"] | null;
            /** Est Cost Usd */
            est_cost_usd?: number | null;
        };
        /**
         * ClarifyTurn
         * @description Agent asked a clarifying question — awaiting a free-text answer.
         */
        ClarifyTurn: {
            /** Session Id */
            session_id: string;
            /**
             * Message Id
             * @description Stable id for this agent turn; dedupe on retry.
             */
            message_id: string;
            /**
             * Agent Message
             * @description Always-present natural-language text.
             */
            agent_message: string;
            progress?: components["schemas"]["GenerateProgress"] | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "clarifying";
        };
        /**
         * Difficulty
         * @enum {string}
         */
        Difficulty: "beginner" | "handy" | "pro";
        /**
         * GenerateMessageCreate
         * @description §11 POST /generate/sessions/{id}/messages — one user turn.
         *
         *     Conversation state lives server-side keyed by session_id (§7.1), so a turn is
         *     tiny: EITHER a free-text reply OR selecting a previously proposed candidate
         *     (by its ``Candidate.id``). Exactly one of the two must be set.
         */
        GenerateMessageCreate: {
            /**
             * Message
             * @description A free-text user turn.
             */
            message?: string | null;
            /**
             * Select Candidate Id
             * @description Accept a proposed candidate by its id (from a ProposeTurn).
             */
            select_candidate_id?: string | null;
        };
        /**
         * GenerateProgress
         * @description Rough progress sense for the bounded chat (§7.1: 'Design step · 3 of 5').
         */
        GenerateProgress: {
            /**
             * Label
             * @description e.g. "Design step".
             */
            label: string;
            /** Current */
            current: number;
            /**
             * Total
             * @description Agent may not always know the total up front.
             */
            total?: number | null;
        };
        /**
         * GenerateSessionCreate
         * @description §11 POST /generate/sessions — the setup payload (mock 1d).
         */
        GenerateSessionCreate: {
            /**
             * Description
             * @description Short free-text description (or the idea chip) of what to build.
             */
            description: string;
            skill_level: components["schemas"]["SkillLevel"];
            budget_band: components["schemas"]["BudgetBand"];
        };
        /**
         * GenerateSessionStart
         * @description Response for POST /generate/sessions.
         */
        GenerateSessionStart: {
            /** Session Id */
            session_id: string;
            /**
             * Agent Message
             * @description The agent's opening message.
             */
            agent_message: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Status
             * @default ok
             */
            status: string;
        };
        /** Material */
        Material: {
            /** Name */
            name: string;
            /** Quantity */
            quantity: number;
            /** Unit */
            unit: string;
            /** Est Cost Usd */
            est_cost_usd: number;
            /** Where To Find */
            where_to_find: string;
            /** Notes */
            notes: string;
        };
        /** MaterialRead */
        MaterialRead: {
            /** Id */
            id: number;
            /** Project Id */
            project_id: number;
            /** Name */
            name: string;
            /** Quantity */
            quantity: number;
            /** Unit */
            unit: string;
            /** Est Cost Usd */
            est_cost_usd: number;
            /** Where To Find */
            where_to_find: string;
            /** Notes */
            notes: string;
            /**
             * Checked
             * @description Runtime: toggled from the shopping cart.
             */
            checked: boolean;
        };
        /**
         * MaterialUpdate
         * @description §11 PATCH /projects/{id}/materials/{mid} — toggle checked.
         */
        MaterialUpdate: {
            /** Checked */
            checked: boolean;
        };
        /** ModuleRead */
        ModuleRead: {
            /** Id */
            id: number;
            /** Slug */
            slug: string;
            /** Name */
            name: string;
            /** Description */
            description: string;
        };
        /** PhotoRead */
        PhotoRead: {
            /** Id */
            id: number;
            /** Project Id */
            project_id: number;
            /**
             * Step Id
             * @description null ⇒ project-level photo (§5).
             */
            step_id?: number | null;
            /** Storage Key */
            storage_key: string;
            /** Caption */
            caption?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** ProjectMeta */
        ProjectMeta: {
            /** Name */
            name: string;
            /**
             * Module
             * @description Module slug, e.g. "mechanic".
             */
            module: string;
            /** Skill Focus */
            skill_focus: string[];
            difficulty: components["schemas"]["Difficulty"];
            time_budget: components["schemas"]["TimeBudget"];
            /** Estimated Cost Usd */
            estimated_cost_usd: number;
            /**
             * Summary
             * @description One-paragraph description of the finished piece and what you'll learn.
             */
            summary: string;
            /** Workspace Required */
            workspace_required: string;
        };
        /**
         * ProjectRead
         * @description Full hydrated project (§11 GET /projects/{id}): spec + state + research +
         *     photos + retrospective.
         */
        ProjectRead: {
            /** Id */
            id: number;
            /** User Id */
            user_id: number;
            /** Module Id */
            module_id: number;
            /** Name */
            name: string;
            /**
             * Slug
             * @description Powers URLs, e.g. /my-mechanic/<slug>/… (§16).
             */
            slug: string;
            /** Skill Focus */
            skill_focus: string[];
            difficulty: components["schemas"]["Difficulty"];
            time_budget: components["schemas"]["TimeBudget"];
            /** Estimated Cost Usd */
            estimated_cost_usd: number;
            /** Summary */
            summary: string;
            /** Workspace Required */
            workspace_required: string;
            status: components["schemas"]["ProjectStatus"];
            /** Spec Version */
            spec_version: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Materials */
            materials: components["schemas"]["MaterialRead"][];
            /** Tools */
            tools: components["schemas"]["ToolRead"][];
            /** Steps */
            steps: components["schemas"]["StepRead"][];
            /** Research Topics */
            research_topics: components["schemas"]["ResearchTopicRead"][];
            /** Photos */
            photos: components["schemas"]["PhotoRead"][];
            retrospective?: components["schemas"]["RetrospectiveRead"] | null;
        };
        /**
         * ProjectSpec
         * @description The full project spec (§6). This is the request body for the import path
         *     (``POST /projects``) and the response body for generation finalize
         *     (``POST /generate/sessions/{id}/finalize``).
         */
        ProjectSpec: {
            /**
             * Schema Version
             * @description Spec schema version. Required and pinned; versioned from day one.
             * @constant
             */
            schema_version: "1.0";
            project: components["schemas"]["ProjectMeta"];
            /** Materials */
            materials: components["schemas"]["Material"][];
            /** Tools */
            tools: components["schemas"]["Tool"][];
            /** Steps */
            steps: components["schemas"]["Step"][];
            /** Research Topics */
            research_topics: components["schemas"]["ResearchTopic"][];
        };
        /**
         * ProjectStatus
         * @description §5 projects.status.
         * @enum {string}
         */
        ProjectStatus: "planning" | "active" | "complete";
        /**
         * ProjectStatusUpdate
         * @description §11 PATCH /projects/{id} — update status.
         */
        ProjectStatusUpdate: {
            status: components["schemas"]["ProjectStatus"];
        };
        /**
         * ProjectSummary
         * @description List view (§11 GET /projects → the 1a 'Your projects' grid). Row-level
         *     fields only; no hydrated children.
         */
        ProjectSummary: {
            /** Id */
            id: number;
            /** User Id */
            user_id: number;
            /** Module Id */
            module_id: number;
            /** Name */
            name: string;
            /**
             * Slug
             * @description Powers URLs, e.g. /my-mechanic/<slug>/… (§16).
             */
            slug: string;
            /** Skill Focus */
            skill_focus: string[];
            difficulty: components["schemas"]["Difficulty"];
            time_budget: components["schemas"]["TimeBudget"];
            /** Estimated Cost Usd */
            estimated_cost_usd: number;
            /** Summary */
            summary: string;
            /** Workspace Required */
            workspace_required: string;
            status: components["schemas"]["ProjectStatus"];
            /** Spec Version */
            spec_version: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * ProposeTurn
         * @description Agent proposed 2–3 candidate projects — awaiting a pick (§7.1, capped at 3).
         */
        ProposeTurn: {
            /** Session Id */
            session_id: string;
            /**
             * Message Id
             * @description Stable id for this agent turn; dedupe on retry.
             */
            message_id: string;
            /**
             * Agent Message
             * @description Always-present natural-language text.
             */
            agent_message: string;
            progress?: components["schemas"]["GenerateProgress"] | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "proposing";
            /** Candidates */
            candidates: components["schemas"]["Candidate"][];
        };
        /**
         * ReadyTurn
         * @description Agent has enough ('✓ Ready to generate documents') — client may call finalize.
         */
        ReadyTurn: {
            /** Session Id */
            session_id: string;
            /**
             * Message Id
             * @description Stable id for this agent turn; dedupe on retry.
             */
            message_id: string;
            /**
             * Agent Message
             * @description Always-present natural-language text.
             */
            agent_message: string;
            progress?: components["schemas"]["GenerateProgress"] | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "ready";
        };
        /** ResearchResource */
        ResearchResource: {
            /** Title */
            title: string;
            /** Url */
            url: string;
            /**
             * Type
             * @description e.g. "video", "article".
             */
            type: string;
        };
        /** ResearchTopic */
        ResearchTopic: {
            /** Topic */
            topic: string;
            /** Why */
            why: string;
            /**
             * Resources
             * @description May arrive empty from generation; the research web-search pass (§7.2) fills them.
             */
            resources: components["schemas"]["ResearchResource"][];
        };
        /** ResearchTopicRead */
        ResearchTopicRead: {
            /** Id */
            id: number;
            /** Project Id */
            project_id: number;
            /** Topic */
            topic: string;
            /** Why */
            why: string;
            /** Resources */
            resources: components["schemas"]["ResearchResource"][];
        };
        /** RetrospectiveRead */
        RetrospectiveRead: {
            /** Id */
            id: number;
            /** Project Id */
            project_id: number;
            /** What Went Well */
            what_went_well: string;
            /** What I Would Do Differently */
            what_i_would_do_differently: string;
            /** Skills Practiced */
            skills_practiced: string[];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * RetrospectiveUpsert
         * @description §11 PATCH /projects/{id}/retrospective — upsert retrospective.
         */
        RetrospectiveUpsert: {
            /** What Went Well */
            what_went_well: string;
            /** What I Would Do Differently */
            what_i_would_do_differently: string;
            /** Skills Practiced */
            skills_practiced: string[];
        };
        /**
         * ShopInventoryCreate
         * @description §11 POST /shop/inventory.
         */
        ShopInventoryCreate: {
            /** Tool Name */
            tool_name: string;
            /** Category */
            category?: string | null;
            /** Notes */
            notes?: string | null;
        };
        /** ShopInventoryRead */
        ShopInventoryRead: {
            /** Id */
            id: number;
            /** User Id */
            user_id: number;
            /** Tool Name */
            tool_name: string;
            /** Category */
            category?: string | null;
            /** Notes */
            notes?: string | null;
        };
        /**
         * SkillLevel
         * @description Generation setup skill level (§7.1 / mock 1d). Mirrors spec difficulty.
         * @enum {string}
         */
        SkillLevel: "beginner" | "handy" | "pro";
        /** Step */
        Step: {
            /** Order */
            order: number;
            /** Title */
            title: string;
            /**
             * Instruction
             * @description Detailed novice-level instruction. Assume no prior knowledge.
             */
            instruction: string;
            /** Safety Note */
            safety_note: string;
            /** Est Time Minutes */
            est_time_minutes: number;
            /** Tools Used */
            tools_used: string[];
            /** Materials Used */
            materials_used: string[];
        };
        /** StepRead */
        StepRead: {
            /** Id */
            id: number;
            /** Project Id */
            project_id: number;
            /** Order */
            order: number;
            /** Title */
            title: string;
            /** Instruction */
            instruction: string;
            /** Safety Note */
            safety_note: string;
            /** Est Time Minutes */
            est_time_minutes: number;
            /** Tools Used */
            tools_used: string[];
            /** Materials Used */
            materials_used: string[];
            /**
             * Completed
             * @description Runtime.
             */
            completed: boolean;
            /**
             * Note
             * @description Runtime: per-step learning ('where I got stuck').
             */
            note?: string | null;
        };
        /**
         * StepUpdate
         * @description §11 PATCH /projects/{id}/steps/{sid} — toggle completed, set note.
         */
        StepUpdate: {
            /** Completed */
            completed?: boolean | null;
            /** Note */
            note?: string | null;
        };
        /**
         * TimeBudget
         * @enum {string}
         */
        TimeBudget: "afternoon" | "weekend" | "multi-weekend";
        /** Tool */
        Tool: {
            /** Name */
            name: string;
            /** Essential */
            essential: boolean;
            /** Est Cost Usd */
            est_cost_usd: number;
            /** Notes */
            notes: string;
            /** Alternatives */
            alternatives: string;
        };
        /** ToolRead */
        ToolRead: {
            /** Id */
            id: number;
            /** Project Id */
            project_id: number;
            /** Name */
            name: string;
            /** Essential */
            essential: boolean;
            /** Est Cost Usd */
            est_cost_usd: number;
            /** Notes */
            notes: string;
            /** Alternatives */
            alternatives: string;
            /**
             * Owned
             * @description Runtime: set by the shop diff (§8).
             */
            owned: boolean;
            /**
             * Acquire
             * @description Runtime: set by the shop diff (§8).
             */
            acquire: boolean;
            /**
             * Checked
             * @description Runtime: for in-cart use.
             */
            checked: boolean;
        };
        /**
         * ToolUpdate
         * @description §11 PATCH /projects/{id}/tools/{tid} — toggle checked / mark owned.
         */
        ToolUpdate: {
            /** Checked */
            checked?: boolean | null;
            /** Owned */
            owned?: boolean | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    list_modules_modules_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModuleRead"][];
                };
            };
        };
    };
    get_module_modules__slug__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModuleRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_projects_projects_get: {
        parameters: {
            query?: {
                module?: string | null;
                status?: components["schemas"]["ProjectStatus"] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_project_projects_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectSpec"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_project_projects__project_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_project_projects__project_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_project_projects__project_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectStatusUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_material_projects__project_id__materials__material_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: number;
                material_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MaterialUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MaterialRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_tool_projects__project_id__tools__tool_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: number;
                tool_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ToolUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ToolRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_step_projects__project_id__steps__step_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: number;
                step_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StepUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StepRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upsert_retrospective_projects__project_id__retrospective_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RetrospectiveUpsert"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RetrospectiveRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_inventory_shop_inventory_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShopInventoryRead"][];
                };
            };
        };
    };
    add_inventory_shop_inventory_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ShopInventoryCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShopInventoryRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_inventory_shop_inventory__inventory_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                inventory_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_photos_projects__project_id__photos_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PhotoRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_photo_projects__project_id__photos_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_photo_projects__project_id__photos_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PhotoRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_photo_photos__photo_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                photo_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_session_generate_sessions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GenerateSessionCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenerateSessionStart"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    send_message_generate_sessions__session_id__messages_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GenerateMessageCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClarifyTurn"] | components["schemas"]["ProposeTurn"] | components["schemas"]["ReadyTurn"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    finalize_session_generate_sessions__session_id__finalize_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectSpec"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_research_projects__project_id__research_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResearchTopicRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
